# Generated by Django 3.0.7 on 2021-03-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(default='9785679657', max_length=10, unique=True),
        ),
    ]
