# Generated by Django 3.0.7 on 2021-03-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210321_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(default='3368321855', max_length=10, unique=True),
        ),
    ]
