# Generated by Django 3.0.7 on 2021-03-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210321_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(default='6738636314', max_length=10, unique=True),
        ),
    ]
