# Generated by Django 3.0.7 on 2021-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210321_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderId',
            field=models.CharField(default='7098203843', max_length=10, unique=True),
        ),
    ]
