# Generated by Django 3.0.7 on 2021-03-21 12:14

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverauth',
            name='serverurl',
            field=django_cryptography.fields.encrypt(models.URLField(null=True)),
        ),
        migrations.AlterField(
            model_name='serverauth',
            name='adminUsername',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=20, null=True)),
        ),
    ]
