# Generated by Django 3.0.7 on 2021-03-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20210321_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverurl', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='serverauth',
            name='serverurl',
        ),
    ]
