# Generated by Django 3.0.7 on 2021-03-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20210321_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdetails',
            name='server_url',
            field=models.URLField(null=True, unique=True),
        ),
    ]
